### ISSUE TITLE
HTTP

### ISSUE THREAD

**Issue by Dogend233** [iocdacc/vsPlayAudio#1]
![image](https://user-images.githubusercontent.com/41180918/62006296-8d351d80-b171-11e9-92ff-eeabfeb75824.png)
https的网站获取不到歌单，被block掉了，很头痛。。。。

**Comment by iocdacc** [comment]
> ![图片](https://user-images.githubusercontent.com/41180918/62006296-8d351d80-b171-11e9-92ff-eeabfeb75824.png)
> HTTPS的网站获取不到歌单，被块掉了，很头痛....

得抽空改一改  解析服务器用的其他大佬的 没用SSL  所以无法在HTTPS网站使用

**Comment by Dogend233** [comment]
我看了那个项目，我不会弄 XD

**Comment by iocdacc** [comment]
> 我看了那个项目，我不会弄 XD

已经修复了 更新代码后再试试

**Comment by Dogend233** [comment]
嗯Ok可以了

**Comment by iocdacc** [comment]
> 嗯Ok可以了

用别人的解析服务器不是个办法，服务器一凉就用不了了。:joy:
已经添加了手动指定方式，不需要解析服务器了
