### ISSUE TITLE
兄弟。自动播放怎么设置啊》？

### ISSUE THREAD

**Issue by yang9w** [iocdacc/vsPlayAudio#3]
autoplay：ture貌似没有效果咯

**Comment by iocdacc** [comment]
高版本浏览器已经不能自动播放了。
除非满足特殊条件，详情查看以下链接：
[autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

**Comment by yang9w** [comment]
> 高版本浏览器已经不能自动播放了。
> 除非满足特殊条件，详情请查看以下链接：
> [autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

了解。多谢兄弟解答。你的这个播放器真不错。
